### ISSUE TITLE
Dependency update required

### ISSUE THREAD

**Issue by F0Xde** [xacrimon/conc-map-bench#3]
With the current `Cargo.lock` this does not compile on 1.50.0-nightly, after running `cargo update` everything is working fine.

```
    Compiling tracing-subscriber v0.2.15
error[E0277]: can't compare `tracing_core::LevelFilter` with `tracing::level_filters::LevelFilter`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.15/src/filter/env/mod.rs:257:49
    |
257 |             .filter(|directive| directive.level > STATIC_MAX_LEVEL)
    |                                                 ^ no implementation for `tracing_core::LevelFilter < tracing::level_filters::LevelFilter` and `tracing_core::LevelFilter > tracing::level_filters::LevelFilter`
    |
    = help: the trait `PartialOrd<tracing::level_filters::LevelFilter>` is not implemented for `tracing_core::LevelFilter`

error[E0277]: `tracing::level_filters::LevelFilter` doesn't implement `std::fmt::Display`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.15/src/filter/env/mod.rs:319:63
    |
319 |             ctx_note(&format!("the static max level is `{}`", STATIC_MAX_LEVEL));
    |                                                               ^^^^^^^^^^^^^^^^ `tracing::level_filters::LevelFilter` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `tracing::level_filters::LevelFilter`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: required by `std::fmt::Display::fmt`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tracing-subscriber`
```
